spring:
  application:
    name: Application
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo
      auto-offset-reset: earliest
    template:
      default-topic: test-topic